/* DO NOT EDIT THIS FILE - it is machine generated */
#include <C:\Program Files\Java\jdk1.8.0_20\include\jni.h>
/* Header for class javatoc */

#ifndef _Included_javatoc
#define _Included_javatoc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javatoc
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javatoc_intMethod
  (JNIEnv *, jobject, jint);

/*
 * Class:     javatoc
 * Method:    booleanMethod
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_javatoc_booleanMethod
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     javatoc
 * Method:    stringMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javatoc_stringMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     javatoc
 * Method:    intArrayMethod
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_javatoc_intArrayMethod
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
